name: Publish Package

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run type check
              run: bun run typecheck

            - name: Run linter
              run: bun run lint

            - name: Run tests
              run: bun run test

            - name: Build package
              run: bun run build

            - name: Publish to npm
              run: bun publish --access public
